export const UserActionTypes = {
  LOG_IN_USER: 'LOG_IN_USER',
  SIGN_UP_USER: 'SIGN_UP_USER',
  SIGN_OUT_USER: 'SIGN_OUT_USER',
  SEND_RESET_LINK_EMAIL: 'SEND_RESET_LINK_EMAIL',
  CLEAR_SEND_RESET_LINK_EMAIL: 'CLEAR_SEND_RESET_LINK_EMAIL',
  GET_API_TOKEN: 'GET_API_TOKEN',
  GET_USER_DATA: 'GET_USER_DATA',
  CLEAR_TOKEN: 'CLEAR_TOKEN',
};
